name: change time

on:
  workflow_dispatch:
    inputs:
      start:
        type: string
        description: start time
        required: false
      end:
        type: string
        description: end time
        required: false

permissions:
  pull-requests: write
  contents: write

jobs:
  check-inputs:
    if: ${{ github.event.inputs.start == '' && github.event.inputs.end == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: check-inputs
        shell: bash
        run: |
          echo "No changes"

  change-yml:
    if: ${{ github.event.inputs.start != '' || github.event.inputs.end != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set env
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: create-branch
        run: |
          git switch -c fix/change-time-${{ env.CURRENT_DATETIME }}
          git push -u origin fix/change-time-${{ env.CURRENT_DATETIME }}

      - name: change-start
        if: ${{ github.event.inputs.start != '' }}
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.app.start = "${{ github.event.inputs.start }}"' sample.yml

      - name: change-end
        if: ${{ github.event.inputs.end != '' }}
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.app.end = "${{ github.event.inputs.end }}"' sample.yml

      - name: echo
        run: cat sample.yml

    #   - name: commit
    #     run: |
    #       git switch -c fix/change-time-$(date +'%Y%m%d%H%M%S')
